-- See https://github.com/charliermarsh/ruff-lsp
return {
  init_options = {
    settings = {
      args = {
        "--select",
        "E",
        "--select",
        "F",
        "--select",
        "C",
        "--select",
        "I",
        "--select",
        "ARG",
        "--select",
        "PD",
        "--select",
        "B",
        "--select",
        "ICN",
        "--select",
        "PT",
        "--select",
        "SIM",
        "--select",
        "UP",
        "--select",
        "T20",
        "--select",
        "NPY",
        "--ignore",
        "E501",
        "--ignore",
        "C901",
        "--ignore",
        "PT011",
        "--ignore",
        "PT012",
        "--ignore",
        "B006",
        "--ignore",
        "PD901",
      },
    },
  },
}
